### ISSUE TITLE
My phone seems to have died a final death

### ISSUE THREAD

**Issue by madbernard** [benbernard/HomeDir#3]
It froze, restarted, failed to restart, and now seems bricked.  I'm aiming to be home around 6 (545 train); I'll slack from home if I'm there earlier.

**Comment by benbernard** [comment]
If you can see this, I think you should go get a new phone at lunch or something, or I guess we could get you back on your Samsung, but that would suck so much.

**Comment by benbernard** [comment]
You should be able to get an s7 or s7 edge from T-Mobile. I could get one in San mateo

**Comment by benbernard** [comment]
This is quite an innovative solution for communication

**Comment by benbernard** [comment]
Do you have a desk phone number? Can you email me it if so? I guess you can't email or you would've...

**Comment by madbernard** [comment]
I just left a message from a desk phone I can probably use
